### ISSUE TITLE
make the API more idiomatic

### ISSUE THREAD

**Issue by mvdan** [editorconfig/editorconfig-core-go#31]
1) I see many `GetFoo` functions. The `Get` should be removed entirely; `editorconfig.DefinitionForFilename` is already clear enough.

2) The `Serialize` and `Save` APIs could both be replaced by a single `WriterTo` method; see https://golang.org/pkg/io/#WriterTo. Not only is this simpler, but it's also more powerful - it supports streaming data, writing to more than just files on disk, etc.

3) `ParseBytes(data []byte)` should be replaced with `Parse(r io.Reader)`. `ParseFile` could be removed too.

In a way, it seems like this API is ported from another language with no readers and writers, hence all the `[]byte` and reading/writing directly to disk.

I realise this package is a v2, so these probably can't change for now. But I think that if a v3 ever happens, the API could be made much nicer, and these are some ideas for it :)

**Comment by greut** [comment]
:+1: The API may evolve in that direction while keeping backward compatibility until a v3 removes the deprecated calls.

**Comment by mvdan** [comment]
4. `func FnmatchCase(pattern, name string) (bool, error)` could be replaced with `TranslatePattern(pattern string) (string, error)`. Then the result could be used with `regexp.MustCompile(result).MatchString`. This also allows the user to cache the regexp as they wish, use other regexp methods like `Match([]byte) bool`, or even use a third-party regex package.

**Comment by mvdan** [comment]
If small, incremental patches are welcome, I'm happy to send PRs.

**Comment by mvdan** [comment]
For suggestion 4, I just realised you reimplemented much of https://github.com/mvdan/sh/blob/6813a2498bf014ce7b93b98e58a840a24d453994/syntax/pattern.go#L45. My shell package has to implement shell globbing for wildcard expansion, so that low-level API should allow you to remove a lot of code.

I think it would still be useful to expose `TranslatePattern` directly here, so the underlying implementation can be changed in the future, and so that you can provide your own docs.

**Comment by greut** [comment]
> If small, incremental patches are welcome, I'm happy to send PRs.

I'll happily review them.

**Comment by mvdan** [comment]
After taking a closer look and sending that first patch, I'm starting to think it would take me less time to simply design and implement a new API from scratch. I'd do this in a separate repo, and I'd be happy to donate that in the future if you want to make it your module's v3.

The intention is not to compete or to deprecate what's here and what works. Simply, my time is limited, and it's a lot easier to design a good API when backwards compatibility isn't a requirement :)

**Comment by andreynering** [comment]
Hi @mvdan,

I hope I'm not late for the party here.

I bit of history: I started this package when I was one of the active Gitea maintainers, and we wanted to make Gitea integrate nicely with .editorconfig files just like GitHub does. I contacted the Editorconfig team about making this part of the official repo, in a hope to get more help in the future since the initial implementation was incomplete (just good enough for an initial use by Gitea).

Also, I was noobier in Go at the time, so your blame on this package being "no idiomatic Go" is perhaps justified (specially because I haven't invested much time on this package since then).

Even so, I strongly disagree with you about splitting our efforts into different repos.

There has been recent effort (thanks @10sr and @greut for that!) on make this run the official Editorconfig test suite, and on making most tests pass (there's still a few missing). By splitting our efforts, you'll miss our efforts on making this implementation complete, and we'll miss your work on improving the performance/usability of the code.

Although I am not officially part of Editorconfig, I'm sure you'd be accepted as a maintainer (if you're willing to). And if we need to push v3 to make the necessary changes possible, let it be.

**Comment by mvdan** [comment]
Thanks for your comment @andreynering.

While I generally agree that starting anew is a bad idea, I clearly think it's reasonable here. The design would be very different, the choice of libraries too, and the API wouldn't really look the same at all. So it wouldn't reuse code, and it would be a big problem to be constrained by the current v2 compatibility promise.

Like I said before, once this is finished I'm happy to donate it as the official v3 if that's useful, and that can go through code reviews if you prefer. But it won't be incremental changes because that simply doesn't make sense :)

**Comment by andreynering** [comment]
Since @mvdan already took the route of creating another library, I'm closing this issue.

I think we should keep most of the API as is for compatibility reasons. And we don't have plans for v3 just yet.

**Comment by 10sr** [comment]
Sorry for late response.

As for me, I do not mind at all about developing new API instead of reusing implementations I wrote 👍 👍 
I know I'm not an experienced Go developer, so it is quite right you think the apis I wrote are "no idiomatic Go".
